#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2026 Numen Games S.L.
# SPDX-License-Identifier: AGPL-3.0-only
"""The fleet machine's reconciler: what runs here equals what the order book says.

Runs every minute from a systemd timer. It pulls the order book, keeps the
orders whose `server` is this machine's alias, renders a docker-compose file
and a Caddyfile from them, and asks Docker to make the containers match.
A world whose order says `stopped`, or whose order is gone, is taken down and
its folder on disk is left alone. A world with no keys on this machine is
skipped and reported — it never starts with an empty admin code.

The machine never writes to git. It holds no GitHub credential: the order
book is public and is pulled like anyone would.

Two rails against a bad merge on the book: this file is INSTALLED once by
bootstrap.sh (to /usr/local/sbin) and never run from the pulled tree, so a
merged pull request changes orders, not code; and an order is obeyed only if
its image comes from the house's registry and its domain is under the
house's zone.

Pure functions first (select, render), the shell last (main). The tests in
tests/test_machine.py cover the pure part; the shell part is three commands.
"""

from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
from pathlib import Path

BOOK = Path("/srv/fleet/book")  # the clone of numinia-assets
HOME = Path("/srv/fleet")  # data/, env/, run/ live here, outside the clone
ALIAS_FILE = Path("/etc/fleet/alias")
CADDY_IMAGE = "caddy:2-alpine"
SLUG = re.compile(r"^[a-z0-9]+(?:-[a-z0-9]+)*$")
REGISTRY = "ghcr.io/numengames/"  # the only place an engine image may come from
ZONE = ".numen.games"  # the only zone a world's domain may sit in


def trusted(order: dict) -> str | None:
    """Why an order is refused even though it names this machine; None when it is fine."""
    image, domain = str(order.get("image", "")), str(order.get("domain", ""))
    if not image.startswith(REGISTRY):
        return f"image {image!r} is not from {REGISTRY}"
    if not domain.endswith(ZONE) or domain.count(".") != ZONE.count("."):
        return f"domain {domain!r} is not one label under {ZONE}"
    return None


def read_orders(folder: Path) -> list[dict]:
    """Every order in the folder, as dicts, sorted by id. Malformed files are skipped loudly."""
    orders = []
    for path in sorted(folder.glob("*.json")):
        try:
            order = json.loads(path.read_text(encoding="utf-8"))
        except json.JSONDecodeError as error:
            print(f"skip {path.name}: not JSON ({error.msg})", file=sys.stderr)
            continue
        if isinstance(order, dict) and order.get("id") == path.stem:
            orders.append(order)
        else:
            print(f"skip {path.name}: id does not match the file", file=sys.stderr)
    return orders


def select_orders(orders: list[dict], alias: str) -> list[dict]:
    """The orders this machine obeys: its alias, a sane id, a trusted image and domain."""
    mine = []
    for o in orders:
        if o.get("server") != alias or not SLUG.match(str(o.get("id", ""))):
            continue
        why = trusted(o)
        if why:
            print(f"refuse {o['id']}: {why}", file=sys.stderr)
            continue
        mine.append(o)
    return mine


def split_by_keys(orders: list[dict], env_dir: Path) -> tuple[list[dict], list[dict]]:
    """Running orders with keys on this machine, and running orders without them."""
    ready, keyless = [], []
    for o in orders:
        if o.get("state") != "running":
            continue
        (ready if (env_dir / f"{o['id']}.env").is_file() else keyless).append(o)
    return ready, keyless


def render_compose(running: list[dict], home: Path) -> str:
    """One Caddy, one service per running world. Only Caddy publishes ports."""
    lines = [
        "# Generated by open-worlds/machine/reconcile.py — do not edit, change the order.",
        "services:",
        "  caddy:",
        f"    image: {CADDY_IMAGE}",
        "    restart: unless-stopped",
        '    ports: ["80:80", "443:443"]',
        "    volumes:",
        f"      - {home}/run/Caddyfile:/etc/caddy/Caddyfile:ro",
        f"      - {home}/run/caddy-data:/data",
        f"      - {home}/run/caddy-config:/config",
    ]
    for o in running:
        wid, domain, limits = o["id"], o["domain"], o["limits"]
        lines += [
            f"  {wid}:",
            f"    image: {o['image']}",
            "    restart: unless-stopped",
            f"    env_file: {home}/env/{wid}.env",
            "    environment:",
            "      WORLD: world",
            "      PORT: '3000'",
            "      ASSETS: local",
            "      DB_URI: local",
            "      COLLECTIONS: local",
            f"      PUBLIC_WS_URL: wss://{domain}/ws",
            f"      PUBLIC_API_URL: https://{domain}/api",
            f"      PUBLIC_ASSETS_URL: https://{domain}/assets",
            f"      PUBLIC_MAX_UPLOAD_SIZE: '{limits['maxUploadMb']}'",
            "    volumes:",
            f"      - {home}/data/{wid}:/app/world",
            "    deploy:",
            "      resources:",
            "        limits:",
            f"          memory: {limits['memory']}",
            f"          cpus: '{limits['cpus']}'",
        ]
    return "\n".join(lines) + "\n"


def render_caddyfile(running: list[dict]) -> str:
    """One site per running world; Caddy issues the certificate and forwards the WebSocket."""
    blocks = ["# Generated by open-worlds/machine/reconcile.py — do not edit, change the order."]
    for o in running:
        blocks.append(f"{o['domain']} {{\n\treverse_proxy {o['id']}:3000\n}}")
    return "\n\n".join(blocks) + "\n"


def plan(book: Path, home: Path, alias: str) -> dict:
    """Everything the shell part needs, computed without touching Docker."""
    mine = select_orders(read_orders(book / "open-worlds"), alias)
    ready, keyless = split_by_keys(mine, home / "env")
    stopped = [o["id"] for o in mine if o.get("state") == "stopped"]
    return {
        "alias": alias,
        "running": [o["id"] for o in ready],
        "stopped": stopped,
        "keyless": [o["id"] for o in keyless],
        "compose": render_compose(ready, home),
        "caddyfile": render_caddyfile(ready),
    }


def sh(*cmd: str) -> None:
    subprocess.run(cmd, check=True)


def apply(p: dict, home: Path) -> None:
    run = home / "run"
    run.mkdir(parents=True, exist_ok=True)
    for wid in p["running"]:
        (home / "data" / wid).mkdir(parents=True, exist_ok=True)
    (run / "docker-compose.yml").write_text(p["compose"], encoding="utf-8")
    (run / "Caddyfile").write_text(p["caddyfile"], encoding="utf-8")
    sh("docker", "compose", "-f", str(run / "docker-compose.yml"), "up", "-d", "--remove-orphans")


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description="Make this machine's containers match the order book.")
    ap.add_argument("--book", type=Path, default=BOOK)
    ap.add_argument("--home", type=Path, default=HOME)
    ap.add_argument("--alias", default=None, help="defaults to /etc/fleet/alias")
    ap.add_argument("--no-pull", action="store_true", help="do not git pull the book first")
    ap.add_argument("--dry-run", action="store_true", help="print the plan, touch nothing")
    args = ap.parse_args(argv)
    alias = args.alias or ALIAS_FILE.read_text(encoding="utf-8").strip()
    if not args.no_pull and not args.dry_run:
        sh("git", "-C", str(args.book), "pull", "--ff-only", "--quiet")
    p = plan(args.book, args.home, alias)
    for wid in p["keyless"]:
        print(f"{wid}: order says running but {args.home}/env/{wid}.env is missing — not started", file=sys.stderr)
    if args.dry_run:
        print(json.dumps({k: p[k] for k in ("alias", "running", "stopped", "keyless")}, indent=2))
        print(p["compose"])
        print(p["caddyfile"])
        return 0
    apply(p, args.home)
    print(f"{alias}: running {p['running']} stopped {p['stopped']} keyless {p['keyless']}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
